#!/bin/sh

NOTEBOOK=eDP1
MONITOR=HDMI1
MODE=1920x1200

if xrandr -q | grep "$MONITOR" > /dev/null 2>&1; then
    xrandr --output $MONITOR --mode $MODE
    sleep 5
    xrandr --output $NOTEBOOK --off
fi

